### ISSUE TITLE
Is this even used?

### ISSUE THREAD

**Issue by theTisch21** [FRC-1294/frc-1294.github.io#34]
@timtim17 
Do we/does anyone plan on actually using this repo? It hasn't had any commits in a while and dependencies are out of date.

**Comment by timtim17** [comment]
Hey! It's a pretty dead repo. I was playing around with it making a custom website to get us off of Wordpress again (custom website => more flexibility?). I liked the style at the time, and it is *technically* still up at [https://jekyll.team1294.org/](https://jekyll.team1294.org/). However, iirc last I heard the team changed branding again, so most of it is out of date.

I personally like the style (maybe biased because of the time investment), but it probably makes more sense for someone who's actually still around on the team to do what they want with it.

**Comment by theTisch21** [comment]
I can confirm, we did change our branding again. I'm going to archive this, and if someone wants to use this they can un-archive it and work on it.
